### ISSUE TITLE
Buildout fails with 'ValueError: ('No requirements found', '')'

### ISSUE THREAD

**Issue by tisto** [plone/plone.recipe.codeanalysis#115]
It seems like this line works only for more recent zc.buildout/zc.recipe.egg versions:

eggs = self.egg.working_set(extra=self.extensions)[1]

My configuration:

- zc.buildout 1.7.1
- zc.recipe.egg 1.3.2
- plone.recipe.codeanalysis 2.0a2

Trace (after running bin/buildout):

```
While:
  Installing code-analysis.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1866, in main
    getattr(buildout, command)(args)
  File "/home/timo/.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 625, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/timo/.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1345, in _call
    return f()
  File "/home/timo/.buildout/eggs/plone.recipe.codeanalysis-2.0a2-py2.7.egg/plone/recipe/codeanalysis/__init__.py", line 136, in install
    self.install_scripts()
  File "/home/timo/.buildout/eggs/plone.recipe.codeanalysis-2.0a2-py2.7.egg/plone/recipe/codeanalysis/__init__.py", line 169, in install_scripts
    eggs = self.egg.working_set(extra=self.extensions)[1]
  File "/home/timo/.buildout/eggs/zc.recipe.egg-1.3.2-py2.7.egg/zc/recipe/egg/egg.py", line 101, in working_set
    **kw)
  File "/home/timo/.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py", line 1079, in install
    return installer.install(specs, working_set)
  File "/home/timo/.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py", line 875, in install
    for spec in specs]
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2919, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '')
```

**Comment by tisto** [comment]
Found the problem. I was using "flake8-extensions" instead of "flake8-extension". @saily can we amend the recipe to use "flake8-extensions"?

**Comment by tisto** [comment]
Ok. I was wrong. flake8-extension just works because it is ignored. Will fix the README.

**Comment by saily** [comment]
@tisto anything to do here?

**Comment by tisto** [comment]
@saily why did you close that issue? This is still a real regression.

**Comment by saily** [comment]
ok, sorry, thought you were wrong and i could close it. should we add a requirement to zc.bulidout>=2.0 or try to get it work in 1.7?
