### ISSUE TITLE
AttributeError: when running any script besides code-analysis

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.recipe.codeanalysis#116]
```bash
# bin/code-analysis-flake8 
Traceback (most recent call last):
  File "bin/code-analysis-flake8", line 19, in <module>
    sys.exit(plone.recipe.codeanalysis.code_analysis_flake8({'_d': '/home/hvelarde/collective/nitf/develop-eggs', 'jshint-exclude': '', 'deprecated-aliases': 'True', 'imports': 'False', 'flake8-exclude': 'bootstrap.py,boostrap-buildout.py,docs,*.egg', 'recipe': 'plone.recipe.codeanalysis', 'find-untranslated': 'False', 'zptlint': 'False', 'flake8-max-complexity': '10', 'jshint': 'True', 'csslint-bin': '/home/hvelarde/collective/nitf/bin/csslint', 'clean-lines-exclude': '', 'i18ndude-bin': '', 'utf8-header': 'False', 'flake8-extensions': '\nflake8-blind-except\nflake8-coding\nflake8-debugger\nflake8-pep257\nflake8-quotes\npep8-naming', 'executable': '/home/hvelarde/collective/buildout.python/python-2.7/bin/python', 'clean-lines': 'True', 'prefer-single-quotes': 'False', 'jshint-bin': 'bin/jshint', 'location': '/home/hvelarde/collective/nitf/parts/code-analysis', 'debug-statements': 'False', '_e': '/home/hvelarde/.buildout/eggs', 'jscs-bin': 'jscs', '_b': '/home/hvelarde/collective/nitf/bin', 'flake8': 'True', 'bin-directory': '/home/hvelarde/collective/nitf/bin', 'jscs-exclude': '', 'pep3101': 'False', 'pre-commit-hook': 'True', 'python': 'buildout', 'find-links': 'http://dist.plone.org/release/4.3-latest/\nhttp://dist.plone.org/thirdparty/', 'string-formatting': 'False', 'return-status-codes': 'True', 'flake8-max-line-length': '79', 'csslint': 'True', 'jscs': 'False', 'eggs-directory': '/home/hvelarde/.buildout/eggs', 'develop-eggs-directory': '/home/hvelarde/collective/nitf/develop-eggs', 'flake8-ignore': 'E501', 'hasattr': 'False', 'zptlint-bin': '', 'jenkins': 'False', 'directory': '/home/hvelarde/collective/nitf/src/collective/nitf', 'multiprocessing': 'True', 'flake8-filesystem': 'False'}))
AttributeError: 'module' object has no attribute 'code_analysis_flake8'
```

**Comment by saily** [comment]
You still have to old script in your bin directory. Remove them and try again.

**Comment by hvelarde** [comment]
same problem


```bash
# rm bin/code-analysis*
(python-2.7)# hvelarde@picovac (master u+3) ~/collective/nitf 
# bin/buildout
Develop: '/home/hvelarde/collective/nitf/.'
/home/hvelarde/.buildout/eggs/setuptools-15.2-py2.7.egg/pkg_resources/__init__.py:197: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Uninstalling code-analysis.
Unused options for buildout: 'package-src' 'package-pep8-ignores' 'package-min-coverage'.
Updating instance.
Updating test.
Installing code-analysis.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-flake8'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-jshint'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-jscs'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-csslint'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-zptlint'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-deprecated-aliases'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-utf8-header'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-clean-lines'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-prefer-single-quotes'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-pep3101'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-imports'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-debug-statements'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-find-untranslated'.
Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-hasattr'.
Install Git pre-commit hook.
Updating createcoverage.
Updating i18ndude.
Updating node.
Updating omelette.
omelette: (While processing egg Pillow) Package 'PIL' is zipped.  Skipping.
omelette: (While processing egg plone.scale) Package 'plone' is zipped.  Skipping.
omelette: (While processing egg argparse) Package 'argparse' is zipped.  Skipping.
Updating rebuild_i18n-sh.
Updating robot.
Updating zopepy.
# bin/code-analysis-flake8 
Traceback (most recent call last):
  File "bin/code-analysis-flake8", line 19, in <module>
    sys.exit(plone.recipe.codeanalysis.code_analysis_flake8({'_d': '/home/hvelarde/collective/nitf/develop-eggs', 'jshint-exclude': '', 'deprecated-aliases': 'True', 'imports': 'False', 'flake8-exclude': 'bootstrap.py,boostrap-buildout.py,docs,*.egg', 'recipe': 'plone.recipe.codeanalysis', 'find-untranslated': 'False', 'zptlint': 'False', 'flake8-max-complexity': '10', 'jshint': 'True', 'csslint-bin': '/home/hvelarde/collective/nitf/bin/csslint', 'clean-lines-exclude': '', 'i18ndude-bin': '', 'utf8-header': 'False', 'flake8-extensions': '\nflake8-blind-except\nflake8-coding\nflake8-debugger\nflake8-quotes\npep8-naming', 'executable': '/home/hvelarde/collective/buildout.python/python-2.7/bin/python', 'clean-lines': 'True', 'prefer-single-quotes': 'False', 'jshint-bin': 'bin/jshint', 'location': '/home/hvelarde/collective/nitf/parts/code-analysis', 'debug-statements': 'False', '_e': '/home/hvelarde/.buildout/eggs', 'jscs-bin': 'jscs', '_b': '/home/hvelarde/collective/nitf/bin', 'flake8': 'True', 'bin-directory': '/home/hvelarde/collective/nitf/bin', 'jscs-exclude': '', 'pep3101': 'False', 'pre-commit-hook': 'True', 'python': 'buildout', 'find-links': 'http://dist.plone.org/release/4.3-latest/\nhttp://dist.plone.org/thirdparty/', 'string-formatting': 'False', 'return-status-codes': 'True', 'flake8-max-line-length': '79', 'csslint': 'True', 'jscs': 'False', 'eggs-directory': '/home/hvelarde/.buildout/eggs', 'develop-eggs-directory': '/home/hvelarde/collective/nitf/develop-eggs', 'flake8-ignore': 'E501', 'hasattr': 'False', 'zptlint-bin': '', 'jenkins': 'False', 'directory': '/home/hvelarde/collective/nitf/src/collective/nitf', 'multiprocessing': 'True', 'flake8-filesystem': 'False'}))
AttributeError: 'module' object has no attribute 'code_analysis_flake8'
```

**Comment by saily** [comment]
can you please do a `cat bin/code-analysis-flake8` because we don't use a `code_analysis_flake8` method any more. this is - as i said - old code.

**Comment by hvelarde** [comment]
```bash
# cat bin/code-analysis-flake8 
#!/home/hvelarde/collective/buildout.python/python-2.7/bin/python

import sys
sys.path[0:0] = [
    '/home/hvelarde/.buildout/eggs/plone.recipe.codeanalysis-2.0a2-py2.7.egg',
    '/home/hvelarde/.buildout/eggs/zc.recipe.egg-1.3.2-py2.7.egg',
    '/home/hvelarde/.buildout/eggs/zc.buildout-1.7.1-py2.7.egg',
    '/home/hvelarde/.buildout/eggs/setuptools-15.2-py2.7.egg',
    '/home/hvelarde/.buildout/eggs/flake8-2.4.0-py2.7.egg',
    '/home/hvelarde/.buildout/eggs/mccabe-0.3-py2.7.egg',
    '/home/hvelarde/.buildout/eggs/pep8-1.5.7-py2.7.egg',
    '/home/hvelarde/.buildout/eggs/pyflakes-0.8.1-py2.7.egg',
    ]


import plone.recipe.codeanalysis

if __name__ == '__main__':
    sys.exit(plone.recipe.codeanalysis.code_analysis_flake8({'_d': '/home/hvelarde/collective/nitf/develop-eggs', 'jshint-exclude': '', 'deprecated-aliases': 'True', 'imports': 'False', 'flake8-exclude': 'bootstrap.py,boostrap-buildout.py,docs,*.egg', 'recipe': 'plone.recipe.codeanalysis', 'find-untranslated': 'False', 'zptlint': 'False', 'flake8-max-complexity': '10', 'jshint': 'True', 'csslint-bin': '/home/hvelarde/collective/nitf/bin/csslint', 'clean-lines-exclude': '', 'i18ndude-bin': '', 'utf8-header': 'False', 'flake8-extensions': '\nflake8-blind-except\nflake8-coding\nflake8-debugger\nflake8-quotes\npep8-naming', 'executable': '/home/hvelarde/collective/buildout.python/python-2.7/bin/python', 'clean-lines': 'True', 'prefer-single-quotes': 'False', 'jshint-bin': 'bin/jshint', 'location': '/home/hvelarde/collective/nitf/parts/code-analysis', 'debug-statements': 'False', '_e': '/home/hvelarde/.buildout/eggs', 'jscs-bin': 'jscs', '_b': '/home/hvelarde/collective/nitf/bin', 'flake8': 'True', 'bin-directory': '/home/hvelarde/collective/nitf/bin', 'jscs-exclude': '', 'pep3101': 'False', 'pre-commit-hook': 'True', 'python': 'buildout', 'find-links': 'http://dist.plone.org/release/4.3-latest/\nhttp://dist.plone.org/thirdparty/', 'string-formatting': 'False', 'return-status-codes': 'True', 'flake8-max-line-length': '79', 'csslint': 'True', 'jscs': 'False', 'eggs-directory': '/home/hvelarde/.buildout/eggs', 'develop-eggs-directory': '/home/hvelarde/collective/nitf/develop-eggs', 'flake8-ignore': 'E501', 'hasattr': 'False', 'zptlint-bin': '', 'jenkins': 'False', 'directory': '/home/hvelarde/collective/nitf/src/collective/nitf', 'multiprocessing': 'True', 'flake8-filesystem': 'False'}))
```

**Comment by saily** [comment]
Sorry, i cannot reproduce. I'm also a little bit confused about this line, because `prefer-single-quotes` is also gone, so there's just no code to generate:

    Generated script '/home/hvelarde/collective/nitf/bin/code-analysis-prefer-single-quotes'.

And this is also old:

    ...
    import plone.recipe.codeanalysis

    if __name__ == '__main__':
        sys.exit(plone.recipe.codeanalysis.code_analysis_flake8({ ... })

can you please check your `site-packages` folder if there's an old `plone.recipe.codeanalysis` available and pinned in your buildout? It seems your buildout is executing following lines on install https://github.com/plone/plone.recipe.codeanalysis/blob/1.1/plone/recipe/codeanalysis/__init__.py#L197-L199

**Comment by hvelarde** [comment]
for some reason (maybe PyPI configuration) buildout is dowloading release 1.1.1 when the package is not pinned.

now is working.

**Comment by tisto** [comment]
@hvelarde maybe because 2.0 is alpha/beta?

**Comment by saily** [comment]
prefer final set in your buildout?
