### ISSUE TITLE
getting flake8-commas to work with flake8 3.3.0

### ISSUE THREAD

**Issue by iham** [plone/plone.recipe.codeanalysis#200]
I am not sure, if flake8-commas are used in the plone community, or if this extension is useful by any means, but as it is documented as a recommend extras which are installed, i guess it should work.

After unpinning all versions of flake8 & related packages (some are really far behind) only flake8-commas seems to make troubles:

with the latest version of commas (0.4.0 & 0.4.1):
```bash
# ./bin/code-analysis-flake8
Flake8..........................[ FAILURE ] in 0.617s
Traceback (most recent call last):
  File "<myproject>/bin/flake8", line 39, in <module>
    sys.exit(flake8.main.cli.main())
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/checker.py", line 317, in run
    self.run_parallel()
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/checker.py", line 286, in run_parallel
    for ret in pool_map:
  File "<mysandbox>/buildout.python/parts/opt/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
AttributeError: 'tuple' object has no attribute 'type'
```

after deactivating multiprocessing (not preferable):
```bash
# ./bin/code-analysis-flake8
Flake8..........................[ FAILURE ] in 0.487s
Traceback (most recent call last):
  File "<myproject>/bin/flake8", line 39, in <module>
    sys.exit(flake8.main.cli.main())
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/checker.py", line 319, in run
    self.run_serial()
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/checker.py", line 303, in run_serial
    checker.run_checks()
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "<myproject>/eggs/flake8-3.3.0-py2.7.egg/flake8/checker.py", line 487, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "<myproject>/eggs/flake8_commas-0.4.1-py2.7.egg/flake8_commas/_base.py", line 262, in run
    for error in get_comma_errors(tokens):
  File "<myproject>/eggs/flake8_commas-0.4.1-py2.7.egg/flake8_commas/_base.py", line 198, in get_comma_errors
    for token in tokens:
  File "<myproject>/eggs/flake8_commas-0.4.1-py2.7.egg/flake8_commas/_base.py", line 122, in simple_tokens
    token = next(tokens)
  File "<myproject>/eggs/flake8_commas-0.4.1-py2.7.egg/flake8_commas/_base.py", line 120, in <genexpr>
    tokens = (t for t in tokens if t.type != tokenize.COMMENT)
AttributeError: 'tuple' object has no attribute 'type'
```

every other package works unpinned in its latest versions:
 + flake8-blind-except = 0.1.1
 + flake8-coding = 1.3.0
 + flake8-debugger = 1.4.0
 + flake8-deprecated = 1.1
 + flake8-isort = 2.1.3
 + flake8-pep3101 = 1.0
 + flake8-plone-api = 1.2
 + flake8-plone-hasattr = 0.1
 + flake8-print = 2.0.2
 + flake8-quotes = 0.9.0
 + flake8-strict = 0.1.4
 + flake8-string-format = 0.2.3
 + flake8-todo = 0.7
 + pep8-naming = 0.4.1

**Comment by hvelarde** [comment]
this problem has nothing to do with this package; it's a known issue on flake8-commas:

https://github.com/flake8-commas/flake8-commas/issues/35
